name: 02 - Manual Trigger

on:
    workflow_dispatch:

jobs:
    manual:
        runs-on: ubuntu-24.04
        steps:
            - name: saludar
              run: echo "Hello World (job manual)!"

            - name: Ver fecha del runner
              run: date

            - name: Ver archivos disponibles
              run: ls -la        